name: "Bob's Bakery"
favicon: null
layout_spectrum: 0.80387
typography_spectrum: 0.47345012053847313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bab4a9'
    - '#ccc4b8'
    - '#dfd8c9'
    - '#9a9286'
    - '#b06463'
  brandStrength: 0.5
  lightness: 0.7115782813634723
  saturation: 0.6875
  rhythmicContrast: 0.4714879193343222
purpose: []
