name: "Bob's Bakery"
favicon: null
layout_spectrum: 0.80387
typography_spectrum: 0.47345012053847313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.21368897217325866
  lightness: 0.7115782813634723
  saturation: 0.11582968523725867
  rhythmicContrast: 0.4714879193343222
purpose: []
